#ifndef REGISTERS_H
#define REGISTERS_H

#define TXRTSCTRL 0x0D  // TXnRTS PIN CONTROL AND STATUS REGISTER
// TXRTSCTRL BITS
#define B2RTS    5      // TRANSMIT BUFFER 2 REQUEST-TO-SEND STATE
#define B1RTS    4      // TRANSMIT BUFFER 1 REQUEST-TO-SEND STATE
#define B0RTS    3      // TRANSMIT BUFFER 0 REQUEST-TO-SEND STATE
#define B2RTSM   2      // TRANSMIT BUFFER 2 REQUEST TRANSMISSION
#define B1RTSM   1      // TRANSMIT BUFFER 1 REQUEST TRANSMISSION
#define B0TRSM   0      // TRANSMIT BUFFER 0 REQUEST TRANSMISSION

// TRANSMIT BUFFER 0 REGISTER MEMORY ADDRESSES
#define TXB0CTRL 0x30   // TRANSMIT BUFFER 0 CONTROL REGISTER
#define TXB0SIDH 0x31   // TRANSMIT BUFFER 0 STANDARD IDENTIFIER HIGH
#define TXB0SIDL 0x32   // TRANSMIT BUFFER 0 STANDARD IDENTIFIER LOW
#define TXB0EID8 0x33   // TRANSMIT BUFFER 0 EXTENDED IDENTIFIER HIGH
#define TXB0EID0 0x34   // TRANSMIT BUFFER 0 EXTENDED IDENTIFIER LOW
#define TXB0DLC  0x35   // TRANSMIT BUFFER 0 DATA LENGTH CODE
#define TXB0D0   0x36   // TRANSMIT BUFFER 0 DATA BYTE 0
#define TXB0D1   0x37   // TRANSMIT BUFFER 0 DATA BYTE 1
#define TXB0D2   0x38   // TRANSMIT BUFFER 0 DATA BYTE 2
#define TXB0D3   0x39   // TRANSMIT BUFFER 0 DATA BYTE 3
#define TXB0D4   0x3A   // TRANSMIT BUFFER 0 DATA BYTE 4
#define TXB0D5   0x3B   // TRANSMIT BUFFER 0 DATA BYTE 5
#define TXB0D6   0x3C   // TRANSMIT BUFFER 0 DATA BYTE 6
#define TXB0D7   0x3D   // TRANSMIT BUFFER 0 DATA BYTE 7
                        
// TRANSMIT BUFFER 1 REGISTER MEMORY ADDRESSES
#define TXB1CTRL 0x40   // TRANSMIT BUFFER 1 CONTROL REGISTER
#define TXB1SIDH 0x41   // TRANSMIT BUFFER 1 STANDARD IDENTIFIER HIGH
#define TXB1SIDL 0x42   // TRANSMIT BUFFER 1 STANDARD IDENTIFIER LOW
#define TXB1EID8 0x43   // TRANSMIT BUFFER 1 EXTENDED IDENTIFIER HIGH
#define TXB1EID0 0x44   // TRANSMIT BUFFER 1 EXTENDED IDENTIFIER LOW
#define TXB1DLC  0x45   // TRANSMIT BUFFER 1 DATA LENGTH CODE
#define TXB1D0   0x46   // TRANSMIT BUFFER 1 DATA BYTE 0
#define TXB1D1   0x47   // TRANSMIT BUFFER 1 DATA BYTE 1
#define TXB1D2   0x48   // TRANSMIT BUFFER 1 DATA BYTE 2
#define TXB1D3   0x49   // TRANSMIT BUFFER 1 DATA BYTE 3
#define TXB1D4   0x4A   // TRANSMIT BUFFER 1 DATA BYTE 4
#define TXB1D5   0x4B   // TRANSMIT BUFFER 1 DATA BYTE 5
#define TXB1D6   0x4C   // TRANSMIT BUFFER 1 DATA BYTE 6
#define TXB1D7   0x4D   // TRANSMIT BUFFER 1 DATA BYTE 7
                        
// TRANSMIT BUFFER 2 REGISTER MEMORY ADDRESSES
#define TXB2CTRL 0x50   // TRANSMIT BUFFER 2 CONTROL REGISTER
#define TXB2SIDH 0x51   // TRANSMIT BUFFER 2 STANDARD IDENTIFIER HIGH
#define TXB2SIDL 0x52   // TRANSMIT BUFFER 2 STANDARD IDENTIFIER LOW
#define TXB2EID8 0x53   // TRANSMIT BUFFER 2 EXTENDED IDENTIFIER HIGH
#define TXB2EID0 0x54   // TRANSMIT BUFFER 2 EXTENDED IDENTIFIER LOW
#define TXB2DLC  0x55   // TRANSMIT BUFFER 2 DATA LENGTH CODE
#define TXB2D0   0x56   // TRANSMIT BUFFER 2 DATA BYTE 0
#define TXB2D1   0x57   // TRANSMIT BUFFER 2 DATA BYTE 1
#define TXB2D2   0x58   // TRANSMIT BUFFER 2 DATA BYTE 2
#define TXB2D3   0x59   // TRANSMIT BUFFER 2 DATA BYTE 3
#define TXB2D4   0x5A   // TRANSMIT BUFFER 2 DATA BYTE 4
#define TXB2D5   0x5B   // TRANSMIT BUFFER 2 DATA BYTE 5
#define TXB2D6   0x5C   // TRANSMIT BUFFER 2 DATA BYTE 6
#define TXB2D7   0x5D   // TRANSMIT BUFFER 2 DATA BYTE 7

// RECEIVE BUFFER 0 REGISTER MEMORY ADDRESSES
#define RXB0CTRL 0x60   // RECEIVE BUFFER 0 CONTROL
#define RXB0SIDH 0x61   // RECEIVE BUFFER 0 STANDARD IDENTIFIER HIGH
#define RXB0SIDL 0x62   // RECEIVE BUFFER 0 STANDARD IDENTIFIER LOW
#define RXB0EID8 0x63   // RECEIVE BUFFER 0 EXTENDED IDENTIFIER HIGH
#define RXB0EID0 0x64   // RECEIVE BUFFER 0 EXTENDED IDENTIFIER LOW
#define RXB0DLC  0x65   // RECEIVE BUFFER 0 DATA LENGTH CODE
#define RXB0D0   0x66   // RECEIVE BUFFER 0 DATA BYTE 0
#define RXB0D1   0x67   // RECEIVE BUFFER 0 DATA BYTE 1
#define RXB0D2   0x68   // RECEIVE BUFFER 0 DATA BYTE 2
#define RXB0D3   0x69   // RECEIVE BUFFER 0 DATA BYTE 3
#define RXB0D4   0x6A   // RECEIVE BUFFER 0 DATA BYTE 4
#define RXB0D5   0x6B   // RECEIVE BUFFER 0 DATA BYTE 5
#define RXB0D6   0x6C   // RECEIVE BUFFER 0 DATA BYTE 6
#define RXB0D7   0x6D   // RECEIVE BUFFER 0 DATA BYTE 7

// RECEIVE BUFFER 1 REGISTER MEMORY ADDRESSES
#define RXB1CTRL 0x70   // RECEIVE BUFFER 1 CONTROL
#define RXB1SIDH 0x71   // RECEIVE BUFFER 1 STANDARD IDENTIFIER HIGH
#define RXB1SIDL 0x72   // RECEIVE BUFFER 1 STANDARD IDENTIFIER LOW
#define RXB1EID8 0x73   // RECEIVE BUFFER 1 EXTENDED IDENTIFIER HIGH
#define RXB1EID0 0x74   // RECEIVE BUFFER 1 EXTENDED IDENTIFIER LOW
#define RXB1DLC  0x75   // RECEIVE BUFFER 1 DATA LENGTH CODE
#define RXB1D0   0x76   // RECEIVE BUFFER 1 DATA BYTE 0
#define RXB1D1   0x77   // RECEIVE BUFFER 1 DATA BYTE 1
#define RXB1D2   0x78   // RECEIVE BUFFER 1 DATA BYTE 2
#define RXB1D3   0x79   // RECEIVE BUFFER 1 DATA BYTE 3
#define RXB1D4   0x7A   // RECEIVE BUFFER 1 DATA BYTE 4
#define RXB1D5   0x7B   // RECEIVE BUFFER 1 DATA BYTE 5
#define RXB1D6   0x7C   // RECEIVE BUFFER 1 DATA BYTE 6
#define RXB1D7   0x7D   // RECEIVE BUFFER 1 DATA BYTE 7

// CONFIGURATION BUFFER 1 REGISTER MEMORY ADDRESSES/BITS
#define CNF1     0x2A   // CONFIGURATION BUFFER 1
#define SJW1     7      // SYNC JUMP WIDTH LENGTH BIT 1
#define SJW0     6      // SYNC JUMP WIDTH LENGTH BIT 0
#define BRP5     5      // BAUD RATE PRESCALER BIT 5
#define BRP4     4      // BAUD RATE PRESCALER BIT 4
#define BRP3     3      // BAUD RATE PRESCALER BIT 3
#define BRP2     2      // BAUD RATE PRESCALER BIT 2
#define BRP1     1      // BAUD RATE PRESCALER BIT 1
#define BRP0     0      // BAUD RATE PRESCALER BIT 0

// CONFIGURATION BUFFER 2 REGISTER MEMORY ADDRESSES/BITS
#define CNF2     0x29   // CONFIGURATION BUFFER 2
#define BTLMODE  7      // PS2 BIT TIME LENGTH BIT
#define SAM      6      // SAMPLE POINT CONFIGURATION BIT
#define PHSEG12  5      // PS1 LENGTH BIT 2
#define PHSEG11  4      // PS1 LENGTH BIT 1
#define PHSEG10  3      // PS1 LENGTH BIT 0
#define PRSEG2   2      // PROPAGATION SEGMENT LENGTH BIT 2
#define PRSEG1   1      // PROPAGATION SEGMENT LENGTH BIT 1
#define PRSEG0   0      // PROPAGATION SEGMENT LENGTH BIT 0

// CONFIGURATION BUFFER 3 REGISTER MEMORY ADDRESSES/BITS
#define CNF3     0x28   // CONFIGURATION BUFFER 3
#define SOF      7      // START-OF-FRAME SIGNAL BIT
#define WAKFIL   6      // WAKE-UP FILTER BIT
#define PHSEG22  2      // PS2 LENGTH BIT 2
#define PHSEG21  1      // PS2 LENGTH BIT 1
#define PHSEG20  0      // PS2 LENGTH BIT 0


























#endif
